# Enedis service.
fetch_datas:
  name: Fetch datas
  description: This service allows you to fetch datas
  fields:
    entry:
      name: Entry
      required: true
      selector:
        config_entry:
          integration: enedis
    power_mode:
      name: Power type
      required: true
      default: daily_consumption
      selector:
        select:
          mode: dropdown
          options:
            - label: Consumption
              value: daily_consumption
            - label: Production
              value: daily_production
    start_date:
      name: Start Date
      description: Start date
      required: true
      selector:
        date:
    end_date:
      name: End Date
      description: End date
      required: true
      selector:
        date:

# Enedis service.
clear_datas:
  name: Clear datas
  description: This service allows you to clear datas
  fields:
    statistic_id:
      name: Statistic Id
      required: true
      selector:
        text: